### ISSUE TITLE
InvalidAsn1Error: 'Expected 0x2: got 0x0'

### ISSUE THREAD

**Issue by douglaspossas** [mcavage/node-asn1#18]
How to solve this issue?

{ [InvalidAsn1Error: Expected 0x2: got 0x0] name: 'InvalidAsn1Error', message: 'Expected 0x2: got 0x0' }

/var/www/courious/node_modules/net-snmp/index.js:918
	var req = this.unregisterRequest (message.pdu.id);
	                                         ^
TypeError: Cannot read property 'pdu' of undefined
    at Session.onMsg (/var/www/courious/node_modules/net-snmp/index.js:918:43)
    at Socket.EventEmitter.emit (events.js:98:17)
    at UDP.onMessage (dgram.js:440:8)

This error message is displayed in an attempt to capture SNMP information from a printer. It would be wrong of LIB ASN1 or LIB net-snmp that makes use of this?

**Comment by pfmooney** [comment]
Judging from the posted stack trace, it appears that there may be a problem in node-net-snmp.  As to why an asn1 error is being throw, you would need to do more investigation.
